### ISSUE TITLE
Cannot install package dependencies

### ISSUE THREAD

**Issue by EggzYy** [UnderstandLingBV/RAGMeUp#1]
Langserve 0.1.0 is not compatible with langchaincore==0.2.4

The info

INFO: pip is looking at multiple versions of langserve to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 2), -r requirements.txt (line 4), -r requirements.txt (line 5), -r requirements.txt (line 6), -r requirements.txt (line 8) and langchain-core==0.2.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested langchain-core==0.2.4
    langchain 0.2.2 depends on langchain-core<0.3.0 and >=0.2.0
    langchain-community 0.2.2 depends on langchain-core<0.3.0 and >=0.2.0
    langchain-huggingface 0.0.2 depends on langchain-core<0.3 and >=0.1.52
    langchain-postgres 0.0.6 depends on langchain-core<0.3 and >=0.1.50
    langchain-text-splitters 0.2.1 depends on langchain-core<0.3.0 and >=0.2.0
    langserve 0.1.0 depends on langchain-core<0.2.0 and >=0.1.0

**Comment by ErikTromp** [comment]
As we don't use langserve explicitly right now, I'll remove it.
